[package]
name = "fringe"
version = "0.0.1"
authors = ["edef <edef@edef.eu>"]
build = "build.rs"

[build-dependencies]
gcc = "0.3.3"

[dependencies]
void = "0.0.5"

[features]
default = ["os", "valgrind"]
os = ["libc"]
valgrind = []

[dependencies.libc]
version = "0.1.6"
optional = true
