[package]
name = "fringe"
version = "0.0.1"
authors = ["edef <edef@edef.eu>"]

[dependencies.void]
version = "1"
default-features = false

[features]
default = ["os", "valgrind"]
os = ["libc"]

[dependencies.libc]
version = "0.1.6"
optional = true

[dependencies.valgrind]
git = "https://github.com/edef1c/libvalgrind"
rev = "9ef793e9549aabfd2d969615180b69d29ce28d88"
optional = true
