[package]
authors = ["Nathan Zadoks <nathan@nathan7.eu>"]
name = "fringe"
version = "0.0.1"

[dependencies.libc]
optional = true
version = "0.1.6"

[dependencies.valgrind]
git = "https://github.com/nathan7/libvalgrind"
optional = true
rev = "7aa8b3fcd3b19994c4669cabc6eae1f96882729d"

[dependencies.void]
default-features = false
version = "1"

[features]
default = ["os", "valgrind"]
os = ["libc"]
